# Generated by Django 4.2.1 on 2023-05-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0003_alter_category_name_alter_category_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
    ]
