# Generated by Django 4.2.1 on 2023-05-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story", "0004_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"ordering": ("-name",)},
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="category", name="slug", field=models.SlugField(unique=True),
        ),
    ]
